title: "Desenvolvimento de Aplicações Web"
description: "Disciplina voltada para o 3º ano do Curso Técnico em Informática do COLTEC/UFMG."
location: "COLTEC/UFMG"
email: joao.montandon [at] dcc [dot] ufmg [dot] br
baseurl: ""

url: "http://coltec-daw.github.io" # replace by your site's url
twitter_username: EduMontandon
github_username:  coltec-daw
author: "João Eduardo Montandon"

# google analytics tracking code, please change the value
g_analytics: "UA-92178302-2"

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: pt-br
close_btn: "Fechar"
home_btn: "Home"
projects_btn: "Projetos"
posts_btn: "News"
imprint_btn: "Imprint"
students_btn: "Turmas"
classes_btn: "Aulas"
name_badge: "Escrito por"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
